# Memory Services Configuration
# Multi-modal memory backends for BioCurator agent system

services:
  # Knowledge Graph Database - Neo4j
  neo4j:
    image: neo4j:5.15-community
    container_name: biocurator-neo4j
    environment:
      - NEO4J_AUTH=neo4j/dev_password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial_size=512m
      - NEO4J_dbms_memory_heap_max_size=1G
      - NEO4J_dbms_memory_pagecache_size=512m
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    networks:
      - biocurator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "--username", "neo4j", "--password", "dev_password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Vector Database - Qdrant
  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: biocurator-qdrant
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - biocurator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Relational Database - PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: biocurator-postgres
    environment:
      - POSTGRES_DB=biocurator_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    networks:
      - biocurator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d biocurator_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Time-series Database - InfluxDB (for agent performance metrics)
  influxdb:
    image: influxdb:2.7-alpine
    container_name: biocurator-influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin_password
      - DOCKER_INFLUXDB_INIT_ORG=biocurator
      - DOCKER_INFLUXDB_INIT_BUCKET=agent_metrics
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dev_token_12345
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - biocurator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  biocurator-network:
    external: true

volumes:
  # Neo4j volumes
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-import:
    driver: local
  neo4j-plugins:
    driver: local

  # Qdrant volumes
  qdrant-data:
    driver: local

  # PostgreSQL volumes
  postgres-data:
    driver: local

  # InfluxDB volumes
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local